mysql:
  # 使用docker时 取容器Id
  host: mysql-stand
  # 使用docker时 取容器运行端口
  port: 3306

redis:
  host: redis
  port: 6379

spring:
  datasource:
    hikari:
      username: well
      password: 123456
  redis:
    password: WLP35Fd10Sp3eQQbX8

logging:
  level:
    root: info