redis:
  host: 127.0.0.1
  port: 6060

mybatis-plus:
  configuration:
    # 打印sql语句,调试用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    org.mybatis: trace
    com.alibaba: trace
    com.baomidou: trace